# Generated by Django 4.2.5 on 2023-09-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RapidApiKey', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='collect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='digg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daystatistics',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
