# Generated by Django 4.2.5 on 2023-09-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tokens_alter_daystatistics_collect_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
