# Generated by Django 4.2.5 on 2023-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_tokens_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='daystatistics',
            options={'verbose_name': 'Статистика дня', 'verbose_name_plural': 'Статистика дней'},
        ),
        migrations.AlterModelOptions(
            name='telegamadmin',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='daystatistics',
            name='deltacollect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daystatistics',
            name='deltacomment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daystatistics',
            name='deltadigg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daystatistics',
            name='deltaplay_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daystatistics',
            name='deltashare_count',
            field=models.IntegerField(default=0),
        ),
    ]
